### ISSUE TITLE
Surface background alpha (feature request)

### ISSUE THREAD

**Issue by guga31bb** [rossdrucker/sportyR#1]
It might be nice to be able to set the alpha for some of the background field plots. My use case is for NFL fields but looking through the examples in the readme, it might also be nice to have this for the soccer field. In both cases, I think this would help the players / ball stand out more.

If I understand the code correctly, this would involve adding an optional parameter to `add_feature()` and setting alpha within the `geom_polygon()` in there, and modifying things like `add_feature(g, grass, color_list$grass_color)`  to pass the additional parameter.

(and thank you for the package which is incredibly useful!)

**Comment by rossdrucker** [comment]
You _do_ understand the code correctly, and that's exactly where it would go. It's not impossible to add that way, but changing the `alpha` parameter is already possible directly through an 8-character hex value for the color. This is demonstrated in the README with the custom college basketball court (look at the `w_two_point_range_color`). 

I'll point you [here](https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4) for the full range of hex "suffixes" to adjust the alpha parameter.

Glad you're enjoying the package!

**Comment by guga31bb** [comment]
Ahh this is perfect thank you!!
