### ISSUE TITLE
Can you remove the caption "Plot made via sportyR"?

### ISSUE THREAD

**Issue by kwartler** [rossdrucker/sportyR#3]
Admittedly this is not a bug but a feature improvement.  As Edward Tufte states "chart junk" should be removed to help with audience focus.  Thus, not only is it bad practice visually but also the caption is hidden in a function `getAnywhere(create_plot_base)`  making it difficult to deal with.  What possible purpose does it serve?  If you are wedded to the idea, why not add the reality that the package is made with ggplot2 which in fact is made with many dependencies?

Overall, love the package though.  Putting it into a forthcoming book.  I appreciate all your efforts for a robust package with this minor suggestion.

**Comment by rossdrucker** [comment]
This is actually a holdover effect from the testing process that I forgot to remove before publishing, sorry! It will be removed in the next release; I'll leave this issue open until then.

Looking forward to seeing the book you're creating as well, please link/share when it's available.

**Comment by kwartler** [comment]
Thx Ross!  Ping me on Linkedin so we can coordinate you getting a copy (next year) when published!

**Comment by rossdrucker** [comment]
I'd be happy to connect! Mind sending me your LinkedIn and/or pinging me instead? Want to make sure I'm reaching out to the right person.
